"""Equipment buffers: which equipment stat line (BonusType 135..165) becomes which EquipBuffDataBase subclass, and how lines of one type combine.

Source (libil2cpp, Code): EquipBuffManager.CreateBuff walks every BonusParameter of the equipped gear; a parameter whose type is already in `buffList` calls the
existing buffer's virtual `SumValue(short)` (base: Value += val), otherwise `EquipBuffDataFactory.Create(slotType, bonusType, value)` builds a new one (0x20e1d00).
Each of the 20 subclasses is decoded here with the symbolic executor: get_BonusType, constructor (initial Value / CalcValue / cap), SumValue (own or the base one),
IsDataStack, and the hook texts (Calc, Function, GetParam, ...). The Details rows read `TryGetEquipBuffer(EquipBuffManager, id).Value / .CalcValue`.

Writes player_status/equip_buffers.json (read by player_status.py and exported into status_spec.json). Asserts the patterns it relies on, so client drift fails loudly.
Run (cwd D:\\toram_re):  python "D:\\toram reverse data\\scripts\\build_equip_buffers.py"
"""
import sys, re, json

sys.path.insert(0, r"D:\toram reverse data\scripts")
sys.path.insert(0, r"D:\toram_re")
import decode_fn as DF
import symexec as S

OUT = r"D:\toram reverse data\player_status\equip_buffers.json"
CLASSES = ["AbsoluteHitRate", "AbsoluteFreeRate", "SelfDmgRate", "ItemDelay", "Guts", "Sacrifice", "HelpMaster", "AvoidBreaker", "GuardBreaker", "BossKiller",
           "PhysicalPursuit", "MagicPursuit", "DamageReflection", "PhysicalBarrier", "MagicBarrier", "RateBarrier", "BarrierSpeed", "GrantStopFlinch", "GrantStopTumble", "GrantStopStun"]
CAP = [re.compile(r"System\.Math\.Min\(value, (\d+)\)$"), re.compile(r"\(value lt (\d+) \? value : (\d+)\)$")]
SUM_CAP = re.compile(r"System\.Math\.Min\(\(Value \+ val\), (\d+)\)$")


def method(cls, name):
    hits = [a for a, n in S.names.items() if n == f"{cls}${'$'}{name}"]
    assert len(hits) == 1, (cls, name, hits)
    return DF.run(hits[0], 60, 8000)[1]


def sets_of(paths):
    out = {}
    for p in paths:
        out.update(p["sets"])
    return out


def main():
    base_sum = sets_of(method("EquipBuffDataBase", "SumValue"))
    assert base_sum.get("<Value>k__BackingField") == "(Value + val)", base_sum
    table = {}
    for cls in CLASSES:
        bid = int(method(cls, "get_BonusType")[0]["ret"][0])
        ctor = sets_of(method(cls, ".ctor"))
        v = ctor.get("<Value>k__BackingField", "0")
        cap, floor = None, None
        for rx in CAP:
            m = rx.match(v)
            if m: cap = int(m.group(1)); break
        if v == "System.Math.Max(0, value)": floor = 0
        elif cap is None: assert v in ("value", "0"), (cls, v)
        own_sum = [a for a, n in S.names.items() if n == f"{cls}$$SumValue"]
        stack = {"rule": "add"}
        calc_value = "<CalcValue>k__BackingField" in ctor
        if own_sum:
            ss = sets_of(DF.run(own_sum[0], 60, 8000)[1])
            m = SUM_CAP.match(ss.get("<Value>k__BackingField", ""))
            assert m, (cls, ss)
            assert int(m.group(1)) == cap, (cls, cap, m.group(1))
            stack = {"rule": "add_cap", "cap": cap}
            if calc_value: assert ss.get("<CalcValue>k__BackingField") == "(CalcValue + val)", (cls, ss)
        elif cap is not None:
            raise AssertionError(f"{cls}: capped constructor without own SumValue")
        ds = [a for a, n in S.names.items() if n == f"{cls}$$get_IsDataStack"]
        hooks = {}
        for h in ("Calc", "Function", "GetParam", "UpdateBufData"):
            for a, n in S.names.items():
                if n == f"{cls}$${h}":
                    ex, paths = DF.run(a, 60, 8000)
                    hooks[h] = [{"if": p["cond"][:4], "sets": p["sets"], "ret": p["ret"][0] if p["ret"] else None} for p in paths[:6]]
        gp = hooks.get("GetParam", [{}])[0].get("ret") if "GetParam" in hooks else None
        assert gp in (None, "Value", "equipType"), (cls, gp)          # base class GetParam returns 0
        table[bid] = {"class": cls, "valueInit": v, "cap": cap, "floor": floor, "calcValue": calc_value, "stack": stack, "getParam": gp or "0",
                      "isDataStack": bool(ds and method(cls, "get_IsDataStack")[0]["ret"][0] == "1"), "hooks": hooks}
    names = {}
    import player_status as P
    for bid, t in table.items():
        t["bonus"] = P.BONUS_BY_ID[bid]
        names[bid] = t["bonus"]
    json.dump({"note": "Generated by scripts/build_equip_buffers.py (Code, libil2cpp). Key = BonusType id.", "buffers": {str(k): v for k, v in sorted(table.items())}},
              open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(len(table), "buffer classes ->", OUT)
    for bid, t in sorted(table.items()):
        print(bid, t["bonus"].ljust(22), t["class"].ljust(16), "cap", t["cap"], "floor", t["floor"], "calcValue", t["calcValue"], "stack", t["stack"]["rule"], "dataStack", t["isDataStack"])


if __name__ == "__main__":
    main()
