"""Hand-written glosses for the variables that appear in damage formulas.
(th, en, unit/label). Evidence label for every entry is `Code` unless the third field says Inferred.
Names come from client method names; the meaning of a term the client never labels is marked Inferred.
"""
P = "IPlayerStatusCalculator."
M = "IMobStatusCalculator."

PLAYER_STAT = {
    "get_Lv": ("เลเวลตัวละคร", "Player level"),
    "get_Str": ("STR สุดท้าย (หลังอุปกรณ์/บัพ/พาสซีฟ)", "Final STR"),
    "get_Int": ("INT สุดท้าย", "Final INT"),
    "get_Vit": ("VIT สุดท้าย", "Final VIT"),
    "get_Agi": ("AGI สุดท้าย", "Final AGI"),
    "get_Dex": ("DEX สุดท้าย", "Final DEX"),
    "get_Crt": ("CRT สุดท้าย", "Final CRT"),
    "get_Luk": ("LUK สุดท้าย", "Final LUK"),
    "get_Men": ("MEN สุดท้าย", "Final MEN"),
    "get_Tec": ("TEC สุดท้าย", "Final TEC"),
    "get_MaxHp": ("HP สูงสุด", "Max HP"),
    "get_MaxMp": ("MP สูงสุด", "Max MP"),
    "get_EqAtk": ("ATK จากอุปกรณ์ (ATK อาวุธ + โบนัส ATK ของอุปกรณ์)", "Equipment ATK"),
    "get_SubEqAtk": ("ATK จากอาวุธรอง", "Sub-weapon equipment ATK"),
    "get_Atk": ("ATK สุดท้าย (พลังโจมตีกายภาพ) คำนวณตามชนิดอาวุธหลัก", "Final physical ATK (per main-weapon formula)"),
    "get_Stable": ("ความเสถียร (Stability) %", "Stability %"),
    "get_Matk": ("MATK สุดท้าย (พลังโจมตีเวท) คำนวณตามชนิดอาวุธหลัก", "Final magic ATK"),
    "get_Hit": ("ความแม่นยำ (Accuracy)", "Accuracy"),
    "get_Flee": ("หลบหลีก (Flee)", "Flee"),
    "get_Def": ("DEF ผู้เล่น", "Player DEF"),
    "get_Mdef": ("MDEF ผู้เล่น", "Player MDEF"),
    "get_EqDef": ("DEF จากอุปกรณ์", "Equipment DEF"),
    "get_Aspd": ("ASPD ความเร็วโจมตี", "Attack speed"),
    "get_Cspd": ("CSPD ความเร็วร่าย", "Cast speed"),
    "get_HpRecovery": ("HP ฟื้นฟูตามธรรมชาติ", "HP natural recovery"),
    "get_MpRecovery": ("MP ฟื้นฟูตามธรรมชาติ", "MP natural recovery"),
    "get_AtkMpRecovery": ("MP ที่ได้ต่อการโจมตี", "MP gained per attack"),
    "get_Critical": ("อัตราคริติคอล (Critical rate)", "Critical rate"),
    "get_CriticalDmg": ("ดาเมจคริติคอลกายภาพ % (ใช้เป็น CriticalDmg/100)", "Physical critical damage %"),
    "get_CriticalMagicDmg": ("ดาเมจคริติคอลเวท %", "Magical critical damage %"),
    "get_ElementPower": ("พลังธาตุ (ใช้ในโบนัสธาตุ)", "Element power (Inferred)"),
    "get_AntiVirus": ("ค่าต้านสถานะผิดปกติ (ชื่อโค้ด AntiVirus; ความหมายยังเป็น Inferred)", "AntiVirus (abnormal-state resist; Inferred)"),
    "get_GuardDelay": ("ดีเลย์การการ์ด", "Guard delay"),
    "get_GuardPower": ("พลังการ์ด % (ตัวคูณดาเมจเมื่อป้องกัน)", "Guard power %"),
    "get_GuardSpeed": ("ความเร็วการ์ด", "Guard speed"),
    "get_AvoidSpeed": ("ความเร็วหลบ (Dodge)", "Avoid speed"),
    "get_AvoidStack": ("จำนวนสแตกหลบ", "Avoid stack"),
    "get_AvoidDelay": ("ดีเลย์หลบ", "Avoid delay"),
    "get_Respawn": ("เวลา/ค่ารีสปอน", "Respawn"),
    "get_SubAtk": ("ATK อาวุธรอง (ใช้ในสูตรคู่ดาบ/อาวุธรอง)", "Sub-weapon ATK"),
    "get_SubStable": ("ความเสถียรอาวุธรอง %", "Sub-weapon stability %"),
    "get_SubMatk": ("MATK อาวุธรอง", "Sub-weapon MATK"),
    "GetDefFact": ("ตัวคูณ DEF (ใช้ตอนโดนตี)", "DEF factor"),
    "GetMdefFact": ("ตัวคูณ MDEF", "MDEF factor"),
    "GetDamageCut": ("ลดดาเมจที่ได้รับ", "Damage cut"),
    "GetNextAtkTime": ("เวลาที่โจมตีครั้งถัดไป", "Next attack time"),
    "GetMotionSpeed": ("ความเร็วท่าทาง", "Motion speed"),
    "GetSkillDelayRate1": ("ตัวคูณดีเลย์สกิลแบบที่ 1", "Skill delay rate 1"),
    "GetSkillDelayRate2": ("ตัวคูณดีเลย์สกิลแบบที่ 2", "Skill delay rate 2"),
    "CalcBaseGuardPower": ("พลังการ์ดพื้นฐาน", "Base guard power"),
    "SetGuildStatusBoost": ("ตั้งค่าบูสต์สเตตัสกิลด์", "Guild status boost setter"),
}
MOB_STAT = {
    "get_MaxHp": ("HP สูงสุดมอนสเตอร์", "Mob max HP"),
    "get_Level": ("เลเวลมอนสเตอร์", "Mob level"),
    "get_NecessaryHit": ("ค่า Flee ของมอน (ต้องมี Hit เท่านี้ถึงไม่พลาด)", "Mob flee (hit needed)"),
    "get_Def": ("DEF มอนสเตอร์", "Mob DEF"),
    "get_MagicDef": ("MDEF มอนสเตอร์", "Mob MDEF"),
    "get_CutAttack": ("ลดพลังโจมตีกายภาพของผู้เล่นต่อมอน (ใช้ใน calcBaseDamage: (100-CutAttack)/100)", "Mob physical cut %"),
    "get_CutMagicAttack": ("ลดพลังโจมตีเวทของผู้เล่นต่อมอน", "Mob magic cut %"),
    "get_GuardProbability": ("โอกาสที่มอนการ์ด %", "Mob guard probability %"),
    "get_AvoidProbability": ("โอกาสที่มอนหลบ %", "Mob avoid probability %"),
    "get_Element": ("ธาตุของมอน", "Mob element"),
    "get_MoveSpeed": ("ความเร็วเคลื่อนที่ของมอน", "Mob move speed"),
    "get_Persona": ("persona (ชนิดบุคลิก AI)", "Persona id"),
    "get_PersonaValue": ("ค่า persona", "Persona value"),
    "get_DamagePercent": ("ตัวคูณดาเมจที่มอนทำ/รับ (DamagePercent)", "Damage percent (Inferred)"),
    "get_NecessaryFleePercent": ("เปอร์เซ็นต์ Flee ที่ต้องมี", "Necessary flee percent"),
    "get_StablePercent": ("ความเสถียรของมอน %", "Mob stable %"),
    "get_ExpDefNormal": ("proration ช่อง Normal ของมอน (ค่าปัจจุบัน %)", "Mob proration, normal-attack slot"),
    "get_ExpDefSkill": ("proration ช่อง Skill ของมอน (ค่าปัจจุบัน %)", "Mob proration, physical-skill slot"),
    "get_ExpDefMagic": ("proration ช่อง Magic ของมอน (ค่าปัจจุบัน %)", "Mob proration, magic slot"),
    "get_Property": ("คุณสมบัติพิเศษของมอน (MobProperty)", "Mob properties"),
    "SetMobStatus": ("ตั้งสถานะมอน", "Set mob status"),
    "CalcDef": ("DEF มอนหลังคำนวณ", "Mob DEF after calc"),
    "CalcMdef": ("MDEF มอนหลังคำนวณ", "Mob MDEF after calc"),
}
ENGINE = {
    "SkillCalcTemplate.GetDamage": ("เอนจินดาเมจกลาง: เดินสเต็ป CalcStep ตามลำดับ (บวกค่าคงที่ → คูณ rate ปัดเศษทุกขั้น → proration → limit)", "Shared damage engine"),
    "PlayerAttackBase.TemplateAssignment": ("ใส่ค่าเอนจินลงทุกสเต็ปของ template (BaseDamage, Def, Crit, Stable, ExpRate, LastDamage ...)", "Fills the engine steps of a damage template"),
    "PlayerAttackBase.calcBaseDamage": ("ดาเมจฐาน = (ATK/MATK + ผลต่างเลเวลผู้เล่น-มอน [+ ATK อาวุธรอง×ความเสถียรรอง/100]) × (100-CutAttack)/100 × ตัวคูณอาวุธ", "Base damage"),
    "PlayerAttackBase.CalcRegistDamage": ("ค่า DEF/MDEF ของมอนที่หักออก (หลังหัก pierce)", "Target DEF/MDEF after pierce"),
    "PlayerAttackBase.CalcPowerResistDamage": ("DEF กายภาพของมอน × (1 − min(1, ทะลุเกราะ))", "Physical DEF after pierce"),
    "PlayerAttackBase.CalcMagicResistDamage": ("MDEF ของมอนหลัง pierce", "Magic DEF after pierce"),
    "PlayerAttackBase.CalcStable": ("ตัวคูณความเสถียรของดาเมจ (กายภาพ/เวท)", "Stability multiplier"),
    "SkillActionBase.CalcStablePercent": ("ความเสถียรกายภาพ %", "Physical stability %"),
    "SkillActionBase.CalcMagicStablePercent": ("ความเสถียรเวท %", "Magic stability %"),
    "PlayerAttackBase.checkCriticalPercent": ("ทอยคริติคอล (Critical − CriticalResist ของมอน จาก 100)", "Critical roll"),
    "PlayerAttackBase.CalcElementBonus": ("โบนัสธาตุ (ได้เปรียบ/เสียเปรียบธาตุ)", "Element advantage multiplier"),
    "PlayerAttackBase.CalcNormalElementWeaponDamageResistRate": ("ตัวคูณต้านธาตุของอาวุธ", "Weapon element resist rate"),
    "PlayerAttackBase.CalcSkillTypeBonusRate": ("โบนัสตามประเภท/ทรีของสกิล (TypeDamageRate)", "Skill-type bonus rate"),
    "PlayerAttackBase.CalcLastDamageRate": ("ตัวคูณดาเมจสุดท้ายรวม (บัพ + มาสเตอรี + เจม + Double Throw ...)", "Total last-damage rate"),
    "PlayerAttackBase.CalcBufferLastDamageRate": ("ตัวคูณดาเมจสุดท้ายจากบัพ/โบนัส", "Last-damage rate from buffs/bonuses"),
    "PlayerAttackBase.CalcGemLastDamageRate": ("ตัวคูณดาเมจสุดท้ายจากเจมคาร์ท", "Gem-cart last-damage rate"),
    "PlayerAttackBase.CalcDistanceResistRate": ("ตัวคูณต้านระยะของมอน", "Distance resist rate"),
    "PlayerAttackBase.CalcHitReaction": ("คำนวณผลการโดน (พลาด/การ์ด/หลบ/ชนะการทอย) ของมอน", "Hit/guard/avoid reaction"),
    "PlayerAttackBase.CalcCostMp": ("MP ที่ใช้ของสกิล", "Skill MP cost"),
    "PlayerAttackBase.CalcCastTime": ("เวลาร่าย (ตาม CSPD)", "Cast time"),
    "PlayerAttackBase.checkAbnormalPercent": ("ทอยโอกาสติดสถานะผิดปกติ", "Abnormal-state chance roll"),
    "PlayerAttackBase.calcFastAttackDamage": ("ดาเมจคงที่ของ Fast Attack", "Fast-attack constant damage"),
    "PlayerAttackBase.calcFastAttackDamageRate": ("ตัวคูณของ Fast Attack", "Fast-attack rate"),
    "ExtensionMethod.ExSkillData.SkillDataExtentionMethod.GetTargetExpRate": ("ค่า proration ปัจจุบันของมอนในช่องที่สกิลใช้ (ExpRate)", "Target proration for this skill"),
    "NormalAttackAction.CalcBaseDamage": ("ดาเมจฐานของการโจมตีปกติ", "Normal-attack base damage"),
    "SkillManager.GetSkillLv": ("เลเวลของสกิลที่ผู้เล่นเรียน", "Learned level of a skill"),
    "SkillBufferManager.TryGetBuf": ("หาบัพของสกิลที่กำลังทำงานอยู่ (out = ตัวบัพ)", "Look up the active buff object for a skill id"),
    "SkillBufferManager.ContainsBuffer": ("มีบัพของสกิลนี้อยู่หรือไม่", "Is the buff of this skill id active"),
    "SkillBufferManager.GetSkillBufferParam": ("ผลรวมพารามิเตอร์ SkillBufferId จากทุกบัพที่ทำงานอยู่", "Sum of a SkillBufferId parameter over active buffs"),
    "SkillBufferManager.AddSelfBuffer": ("ติดบัพให้ตัวเอง", "Add a buff to self"),
    "SkillBufferManager.RemoveSelfBuffer": ("ถอดบัพของสกิลนี้จากตัวเอง", "Remove a buff from self"),
    "SkillBufferDataBase.GetParam": ("ค่าพารามิเตอร์ของบัพตาม SkillBufferId", "Buff parameter by SkillBufferId"),
    "SkillMasteryBase.GetMasteryParam": ("โบนัสพาสซีฟของมาสเตอรีตามเลเวลสกิล", "Passive bonus of a mastery at skill level"),
    "BonusManager.GetBonusValue": ("ผลรวมโบนัส BonusType (ค่าคงที่) จากอุปกรณ์/บัพ", "Sum of a BonusType (flat)"),
    "BonusManager.GetBonusPercentValue": ("ผลรวมโบนัส BonusType เป็น % ", "Sum of a BonusType (percent)"),
    "BonusManager.GetCalcBonusValue": ("ค่าฐาน × (1+โบนัส%) + โบนัสคงที่ ตามคู่ BonusType rate/const", "base × rate + const bonus"),
    "AbnormalStateManager.Contains": ("ตัวละคร/มอนกำลังติดสถานะผิดปกตินี้อยู่หรือไม่", "Has abnormal state"),
    "MathUtil.CheckPercent": ("ทอยโอกาส % (สุ่ม 0-99 < ค่า)", "Percent roll"),
    "SkillActionBase.checkPercent": ("ทอยโอกาส % ของสกิล", "Skill percent roll"),
    "UnityEngine.Random.Range": ("สุ่มค่า", "Random.Range"),
}
OUTPARAM = {
    "TryGetBuf.out2": ("ตัวบัพที่ค้นเจอ (ใช้อ่านฟิลด์ เช่น .Count)", "Buff object returned by TryGetBuf"),
    "TryGetValue.out2": ("ค่าที่ค้นเจอในตาราง/พจนานุกรม (บัพหรือมาสเตอรี) — .Count คือจำนวนสแตกของบัพนับ", "Value found in a dictionary lookup"),
}
