"""Render skills/damage/stats/decoded/*.json into STATS.md + COVERAGE_STATS.md (identical bodies across classes are merged)."""
import json, os, re, hashlib, collections

BASE = r"D:\toram reverse data\skills\damage"
DEC = os.path.join(BASE, "stats", "decoded")
idx = json.load(open(os.path.join(DEC, "index.json"), encoding="utf-8"))
TITLES = {"player": "Player stats (PlayerSecondaryStatus / PrimaryStatus / BattleStatus)", "weapon": "Weapon calculators (EquipItemData.*Calculator)",
          "bonus": "BonusManager", "mob": "Mob stats (IMobStatusCalculator implementations)", "attack": "Damage helpers (PlayerAttackBase / MobAttackBase)",
          "normal": "Normal (non-skill) attack"}


def lines(im):
    L = []
    if im.get("error"): L.append(f"decode error: {im['error']}")
    for c in im.get("cases", []):
        L.append("when " + (" AND ".join(c["common"]) or "always") + (f"   [{len(c['variants'])} variant(s)]" if c.get("variants") else ""))
        L.append(f"  = {c['value']}")
        for v in c.get("variants", [])[:6]: L.append("    or " + (" AND ".join(v) if v else "always"))
        if len(c.get("variants", [])) > 6: L.append(f"    ... {len(c['variants']) - 6} more")
    if im.get("events"):
        L.append("effects:")
        for ev in im["events"][:60]:
            L.append(f"  [{ev['kind']}] {ev['name']} = {ev['value']}" + (f"   when {' AND '.join(ev['when'])}" if ev["when"] else ""))
        if len(im["events"]) > 60: L.append(f"  ... {len(im['events']) - 60} more")
    if im.get("lets"):
        L.append("sub-expressions:")
        for k, x in im["lets"].items(): L.append(f"  {k} = {x}")
    return L


md = ["# Decoded stat / weapon / mob / damage-helper functions", "",
      "Generated by `D:\\toram_re\\render_stats.py` from `stats/decoded/*.json` (forward-merging symbolic execution of `libil2cpp.so`, offline). Label: **Code**.",
      "`_tN` are shared sub-expressions defined at the end of each block. Floats are real values; integer division is `//`.", ""]
cov = ["# Stats coverage", "", "| group | functions | decoded | truncated | error |", "|---|---|---|---|---|"]
bad = []
RESID = {"unnamed field read": re.compile(r"\[(?:\?[a-z]+|this|[\w.<>]+)\+0x[0-9a-f]+\]"), "unresolved indirect call (delegate / stub)": re.compile(r"\?blr|(?<![\w.$])0x[0-9a-f]{6,}\("),
         "unresolved generic method info": re.compile(r"\?mi")}
resid = collections.defaultdict(list)
for g, title in TITLES.items():
    fns = {n: v for n, v in idx.items() if v["group"] == g}
    st = collections.Counter(v["status"] for v in fns.values())
    cov.append(f"| {g} | {len(fns)} | {st['ok']} | {st['trunc']} | {st['error']} |")
    md += [f"## {title}", ""]
    merged = collections.OrderedDict()
    for n, v in fns.items():
        r = json.load(open(os.path.join(DEC, v["file"]), encoding="utf-8"))
        cls, _, fn = n.partition("$$")
        body = lines(r)
        if r.get("returns") != "void":
            txt = " ".join(c["value"] + " " + " ".join(r.get("lets", {}).get(t, "") for t in re.findall(r"_t\d+", c["value"])) for c in r.get("cases", []))
            for k, rx in RESID.items():
                m = rx.search(txt)
                if m: resid[k].append(f"`{n}`: `...{txt[max(0, m.start() - 50):m.end() + 30]}...`")
        h = hashlib.md5((fn + "\n".join(body)).encode("utf-8")).hexdigest()
        merged.setdefault(h, {"fn": fn, "cls": [], "r": r, "body": body})["cls"].append(cls)
        if v["status"] != "ok": bad.append(f"{n} ({v['status']})")
    for m in merged.values():
        cl = m["cls"]
        who = cl[0] + (f" (+{len(cl) - 1} identical: {', '.join(cl[1:6])}{' ...' if len(cl) > 6 else ''})" if len(cl) > 1 else "")
        r = m["r"]
        sig = ", ".join(f"{t} {n}" for t, n in r.get("params", []))
        md += [f"### {who}.{m['fn']}({sig}) -> {r.get('returns')}  @{r['rva']}" + ("  TRUNCATED" if r.get("truncated") else ""), "```", "\n".join(m["body"]) or "(no value / no effects)", "```", ""]
cov += ["", "## Residual unresolved terms inside value-returning functions", ""]
for k, v in resid.items():
    cov += [f"### {k} ({len(v)})", ""] + [f"- {x}" for x in v] + [""]
cov += ["", "Not fully decoded:", ""] + ([f"- `{n}`" for n in bad] or ["- none"])
open(os.path.join(BASE, "STATS.md"), "w", encoding="utf-8").write("\n".join(md))
open(os.path.join(BASE, "COVERAGE_STATS.md"), "w", encoding="utf-8").write("\n".join(cov))
print(len(md), "lines;", len(bad), "not fully decoded")
