"""CORE_FORMULAS.md: the subset of stats/decoded a damage simulator evaluates, plus the input checklist."""
import json, os, re, collections

BASE = r"D:\toram reverse data\skills\damage"
DEC = os.path.join(BASE, "stats", "decoded")
idx = json.load(open(os.path.join(DEC, "index.json"), encoding="utf-8"))
SEL = [
    ("Player: primary -> secondary stats", r"^PlayerSecondaryStatus\$\$(get_(Atk|Matk|EqAtk|SubAtk|SubEqAtk|SubMatk|Stable|SubStable|Critical|CriticalDmg|CriticalMagicDmg|Hit|Flee|Aspd|Cspd|ElementPower|Def|Mdef|EqDef|MaxHp|MaxMp|AtkMpRecovery|Lv)|GetCrt\w*|CalcCriticalDmg|GetDamageCut|GetDefFact|GetMdefFact)$"),
    ("Weapon calculators (ATK / MATK / stable / aspd / hit per weapon type)", r"^EquipItemData(\.\w+Calculator\w*)?\$\$(Calc\w+|calc\w+|SubCalc\w+|CorrectHit)$"),
    ("Mob stats (base class and the field/boss variants that differ)", r"^(MobBattleStatus|BossMobBattleStatus|GuildRaidBossMobBattleStatus|HighRaidBossBattleStatus|DungeonMobBattleStatus|NonTargetDummyMobBattleStatus)\$\$(get_\w+|Calc\w+)$"),
    ("Damage pipeline helpers", r"^(PlayerAttackBase|MobAttackBase)\$\$(Calc(Stable|ElementBonus|ElementKillerBonus|NormalElementWeaponDamageResistRate|DistanceResistRate|SkillTypeBonusRate|LastDamageRate|SkillMasteryLastDamageRate|WeaponCharacteristicsLastDamageRate|BufferLastDamageRate|CobmoRate|DoubleThrowLastDamageRate|BonusLastDamageRate|GemLastDamageRate|PowerResistDamage|MagicResistDamage|RegistDamage|BaseAttack)|Check(Hit|DamageLimit|PlayerDamageUpLimit|AbnormalDamageIncrease|SpecificWeaponBaseDamageRate)|GetSpecificWeaponLastDamageRate)$"),
]


def lines(im):
    L = []
    for c in im.get("cases", []):
        L.append("when " + (" AND ".join(c["common"]) or "always") + (f"   [{len(c['variants'])} variant(s)]" if c.get("variants") else ""))
        L.append(f"  = {c['value']}")
        for v in c.get("variants", [])[:4]: L.append("    or " + (" AND ".join(v) if v else "always"))
        if len(c.get("variants", [])) > 4: L.append(f"    ... {len(c['variants']) - 4} more")
    if im.get("lets"):
        L.append("where:")
        for k, x in im["lets"].items(): L.append(f"  {k} = {x}")
    return L


md = ["# Core formulas for a damage simulator", "",
      "Subset of [`STATS.md`](STATS.md) (generated by `D:\\toram_re\\render_core.py`). Evidence label: **Code** (decoded from `libil2cpp.so`); none checked against an in-game value yet.", "",
      "Evaluation order of the final hit is in `engine.json` (`get_damage`). The functions below produce the numbers that feed it.", ""]
for title, pat in SEL:
    rx = re.compile(pat)
    names = [n for n in idx if rx.match(n)]
    md += [f"## {title} ({len(names)} functions)", ""]
    merged = collections.OrderedDict()
    for n in names:
        r = json.load(open(os.path.join(DEC, idx[n]["file"]), encoding="utf-8"))
        body = lines(r)
        if not body: continue
        cls, _, fn = n.partition("$$")
        merged.setdefault(fn + "\n".join(body), {"fn": fn, "cls": [], "r": r, "body": body})["cls"].append(cls)
    for m in merged.values():
        r = m["r"]; cl = m["cls"]
        sig = ", ".join(f"{t} {n}" for t, n in r.get("params", []))
        who = cl[0] + (f" (+{len(cl) - 1} identical)" if len(cl) > 1 else "")
        md += [f"### {who}.{m['fn']}({sig}) -> {r.get('returns')}", "```", "\n".join(m["body"]), "```", ""]
open(os.path.join(BASE, "CORE_FORMULAS.md"), "w", encoding="utf-8").write("\n".join(md))
print(len(md), "lines")
