"""Game-update driver (PROJECT.md "Game update runbook"). Skips everything that is provably unchanged.

  python update_game.py status
      binary identity (SHA-256 of libil2cpp.so) vs the stored baseline, newest master version vs _history.csv
  python update_game.py baseline
      fingerprint the CURRENT build and store it as the baseline (state/fp_baseline.json). Run once after a full, verified pipeline run.
  python update_game.py install --so NEW/libil2cpp.so --meta NEW/global-metadata.dat
      old binary/dump are archived under state/archive/<sha8>/, the new files are installed, Il2CppDumper is run (dump.cs, script.json),
      the il2cpp stubs, the id->class maps and the GemCart inputs are regenerated by name, new fingerprints are built and diffed against
      the baseline -> state/changed_units.json. Identical binary: nothing is touched and the command says so.
  python update_game.py plan
      prints what has to be re-run for the changed units (skill uids for run_skills.py, whether the stats layer changed, derived steps)
  python update_game.py rebuild
      runs the plan: run_skills.py for the changed skill uids, run_masteries / orphan bufs when needed, then the derived pipeline (pipeline.sh)

Data layer (bundles, masters, text) is independent: python cache.py / decode_all.py / export_*.py; the master parsers stop on any
layout change (exact-EOF rule), so a new data version needs no binary work unless a parser reports a mismatch.
"""
import os, sys, json, shutil, subprocess, hashlib, argparse
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import il2

HERE = os.path.dirname(os.path.abspath(__file__))
ST = il2.STATE
BASE_FP = os.path.join(ST, "fp_baseline.json")
CUR_FP = os.path.join(ST, "fp_current.json")
CHANGED = os.path.join(ST, "changed_units.json")
DUMPER = os.path.join(il2.WORK, "tool", "Il2CppDumper.exe")


def sha(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()


def py(*a, **kw):
    print("  $", "python", *a)
    return subprocess.run([sys.executable, *a], cwd=HERE, env={**os.environ, "PYTHONIOENCODING": "utf-8", "PYTHONHASHSEED": "0"}, **kw)


def status():
    cur = il2.so_sha256()
    base = json.load(open(BASE_FP))["_meta"]["so_sha256"] if os.path.exists(BASE_FP) else None
    print("installed libil2cpp.so", cur[:16], "| baseline", (base or "none")[:16], "->", "SAME" if cur == base else "DIFFERENT / no baseline")
    h = os.path.join(il2.DATA, "TORAM ONLINE BIGDATA", "readable", "masters", "_history.csv")
    if os.path.exists(h):
        rows = [l.split(",") for l in open(h, encoding="utf-8").read().splitlines()[1:] if l]
        newest = max(rows, key=lambda r: r[1])
        print("newest master version in _history.csv:", newest[0], "dated", newest[1])


def baseline():
    py("build_factory_maps.py", "--check", check=True)
    py("fingerprint.py", "build", check=True)
    shutil.copyfile(CUR_FP, BASE_FP)
    print("baseline stored:", BASE_FP)


def adopt_constants():
    """metadata/constants.tsv feeds every enum name (refutil.ENUM). Adopt the one from the new Android metadata unless an existing enum value moved."""
    import csv
    def load(p):
        d = {}
        for r in csv.DictReader(open(p, encoding="utf-8-sig"), delimiter="\t"):
            try: d.setdefault(r["type"], {})[r["field"]] = int(r["value"])
            except (ValueError, KeyError): pass
        return d
    cur, new = os.path.join(il2.DATA, "metadata", "constants.tsv"), os.path.join(il2.WORK, "meta_android", "constants.tsv")
    a, b = load(cur), load(new)
    moved = [(t, f, a[t][f], b[t][f]) for t in a.keys() & b.keys() for f in a[t].keys() & b[t].keys() if a[t][f] != b[t][f]]
    gone = sorted(t for t in a.keys() - b.keys())
    print(f"  constants: {len(a)} -> {len(b)} types, {len(moved)} values moved, {len(gone)} types absent in the new metadata")
    if moved:
        print("  VALUES MOVED (review before adopting, first 20):", moved[:20]); sys.exit(2)
    shutil.copy2(cur, cur + ".bak"); shutil.copy2(new, cur)


def install(so, meta):
    if sha(so) == il2.so_sha256():
        print("binary identical to the installed one: nothing to re-decode. Use the data-layer scripts for new bundles."); return
    arch = os.path.join(ST, "archive", il2.so_sha256()[:8]); os.makedirs(arch, exist_ok=True)
    for f in (il2.SO, os.path.join(il2.DUMP, "dump.cs"), os.path.join(il2.DUMP, "script.json")):
        if os.path.exists(f): shutil.copy2(f, arch)
    shutil.copy2(BASE_FP, arch) if os.path.exists(BASE_FP) else None
    shutil.copy2(so, il2.SO)
    out = il2.DUMP + "_new"
    shutil.rmtree(out, ignore_errors=True); os.makedirs(out)
    print("  $ Il2CppDumper", so, meta, out)
    subprocess.run([DUMPER, so, meta, out], check=True, stdin=subprocess.DEVNULL, cwd=os.path.dirname(DUMPER))
    for f in ("dump.cs", "script.json", "il2cpp.h", "stringliteral.json"):
        shutil.copy2(os.path.join(out, f), os.path.join(il2.DUMP, f))
    for f in ("il2_stubs.json",):
        p = os.path.join(ST, f)
        if os.path.exists(p): os.remove(p)
    py("il2.py", check=True)                         # stub discovery fails loudly when the structure assumptions break
    py("meta_dump.py", meta, os.path.join(il2.WORK, "meta_android"), check=True)
    adopt_constants()
    py("build_factory_maps.py", check=True)
    py("registlet_inputs.py", check=True)
    py("fingerprint.py", "build", check=True)
    if os.path.exists(BASE_FP):
        a, b = json.load(open(BASE_FP)), json.load(open(CUR_FP))
        ka, kb = {k: v for k, v in a.items() if not k.startswith("_")}, {k: v for k, v in b.items() if not k.startswith("_")}
        d = {"changed": sorted(k for k in ka.keys() & kb.keys() if ka[k] != kb[k]), "added": sorted(kb.keys() - ka.keys()), "removed": sorted(ka.keys() - kb.keys())}
        json.dump(d, open(CHANGED, "w"), indent=1)
        print({k: len(v) for k, v in d.items()}, "->", CHANGED)
    else:
        print("no baseline: run `baseline` on the OLD build next time; everything counts as changed")


def plan():
    d = json.load(open(CHANGED))
    ch = d["changed"] + d["added"]
    uids = sorted({int(k.split(":")[1]) for k in ch if k.startswith(("skill:", "buffer:"))})
    print("skills to re-decode:", len(uids), uids[:60], "...")
    print("masteries:", [k for k in ch if k.startswith("mastery:")][:30])
    print("gemcart classes:", [k for k in ch if k.startswith("gemcart:")][:30])
    print("stats/engine layer changed:", "stats:all" in ch, "| removed units:", len(d["removed"]))
    return uids, ch


def rebuild():
    uids, ch = plan()
    if uids: py("run_skills.py", *map(str, uids), check=True)
    if any(k.startswith("mastery:") for k in ch): py("run_masteries.py", check=True)
    if any(k.startswith(("skill:", "buffer:")) for k in ch): py("run_orphan_bufs.py", check=True)
    if "stats:all" in ch:
        for s in ("harvest_stats.py weapon player bonus normal attack mob", "postfix_stats.py", "render_stats.py", "render_core.py"): py(*s.split(), check=True)
    subprocess.run(["bash", os.path.join(HERE, "pipeline.sh")], check=True)
    py("build_damage_type.py", check=True); py("build_registlet.py", check=True)
    shutil.copyfile(CUR_FP, BASE_FP)
    print("rebuild done; baseline advanced to the new build")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("cmd", choices=["status", "baseline", "install", "plan", "rebuild"])
    ap.add_argument("--so"); ap.add_argument("--meta")
    a = ap.parse_args()
    {"status": status, "baseline": baseline, "plan": plan, "rebuild": rebuild}.get(a.cmd, lambda: install(a.so, a.meta))()
