// Assembly: System.Data.dll
// Namespace: System.Data
[DefaultMember("Item")]
[DefaultEvent("CollectionChanged")]
public sealed class ConstraintCollection : InternalDataCollectionBase // TypeDefIndex: 14675
{
	// Fields
	private readonly DataTable _table; // 0x10
	private readonly ArrayList _list; // 0x18
	private int _defaultNameIndex; // 0x20
	private CollectionChangeEventHandler _onCollectionChanged; // 0x28
	private Constraint[] _delayLoadingConstraints; // 0x30
	private bool _fLoadForeignKeyConstraintsOnly; // 0x38

	// Properties
	protected override ArrayList List { get; }
	public Constraint Item { get; }
	internal DataTable Table { get; }
	public Constraint Item { get; }

	// Methods

	// RVA: 0x31DE954 Offset: 0x31DA954 VA: 0x31DE954
	internal void .ctor(DataTable table) { }

	// RVA: 0x31DEA0C Offset: 0x31DAA0C VA: 0x31DEA0C Slot: 12
	protected override ArrayList get_List() { }

	// RVA: 0x31DEA14 Offset: 0x31DAA14 VA: 0x31DEA14
	public Constraint get_Item(int index) { }

	// RVA: 0x31DEB10 Offset: 0x31DAB10 VA: 0x31DEB10
	internal DataTable get_Table() { }

	// RVA: 0x31DEB18 Offset: 0x31DAB18 VA: 0x31DEB18
	public Constraint get_Item(string name) { }

	// RVA: 0x31DED60 Offset: 0x31DAD60 VA: 0x31DED60
	public void Add(Constraint constraint) { }

	// RVA: 0x31DED68 Offset: 0x31DAD68 VA: 0x31DED68
	internal void Add(Constraint constraint, bool addUniqueWhenAddingForeign) { }

	// RVA: 0x31DF6EC Offset: 0x31DB6EC VA: 0x31DF6EC
	public Constraint Add(string name, DataColumn[] columns, bool primaryKey) { }

	// RVA: 0x31DF348 Offset: 0x31DB348 VA: 0x31DF348
	private void AddUniqueConstraint(UniqueConstraint constraint) { }

	// RVA: 0x31DF554 Offset: 0x31DB554 VA: 0x31DF554
	private void AddForeignKeyConstraint(ForeignKeyConstraint constraint) { }

	// RVA: 0x31DF278 Offset: 0x31DB278 VA: 0x31DF278
	private bool AutoGenerated(Constraint constraint) { }

	// RVA: 0x31DF68C Offset: 0x31DB68C VA: 0x31DF68C
	private void ArrayAdd(Constraint constraint) { }

	// RVA: 0x31DF794 Offset: 0x31DB794 VA: 0x31DF794
	private void ArrayRemove(Constraint constraint) { }

	// RVA: 0x31DF530 Offset: 0x31DB530 VA: 0x31DF530
	internal string AssignName() { }

	// RVA: 0x31DF5C4 Offset: 0x31DB5C4 VA: 0x31DF5C4
	private void BaseAdd(Constraint constraint) { }

	// RVA: 0x31DF884 Offset: 0x31DB884 VA: 0x31DF884
	private void BaseGroupSwitch(Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength) { }

	// RVA: 0x31DFA38 Offset: 0x31DBA38 VA: 0x31DFA38
	private void BaseRemove(Constraint constraint) { }

	// RVA: 0x31DFCE4 Offset: 0x31DBCE4 VA: 0x31DFCE4
	internal bool CanRemove(Constraint constraint, bool fThrowException) { }

	// RVA: 0x31DFD14 Offset: 0x31DBD14 VA: 0x31DFD14
	public void Clear() { }

	// RVA: 0x31E0100 Offset: 0x31DC100 VA: 0x31E0100
	public bool Contains(string name) { }

	// RVA: 0x31E0118 Offset: 0x31DC118 VA: 0x31E0118
	internal bool Contains(string name, bool caseSensitive) { }

	// RVA: 0x31DF11C Offset: 0x31DB11C VA: 0x31DF11C
	internal Constraint FindConstraint(Constraint constraint) { }

	// RVA: 0x31DF424 Offset: 0x31DB424 VA: 0x31DF424
	internal UniqueConstraint FindKeyConstraint(DataColumn[] columns) { }

	// RVA: 0x31E029C Offset: 0x31DC29C VA: 0x31E029C
	internal UniqueConstraint FindKeyConstraint(DataColumn column) { }

	// RVA: 0x31E03A8 Offset: 0x31DC3A8 VA: 0x31E03A8
	internal ForeignKeyConstraint FindForeignKeyConstraint(DataColumn[] parentColumns, DataColumn[] childColumns) { }

	// RVA: 0x31E0214 Offset: 0x31DC214 VA: 0x31E0214
	private static bool CompareArrays(DataColumn[] a1, DataColumn[] a2) { }

	// RVA: 0x31DEC04 Offset: 0x31DAC04 VA: 0x31DEC04
	internal int InternalIndexOf(string constraintName) { }

	// RVA: 0x31DF7CC Offset: 0x31DB7CC VA: 0x31DF7CC
	private string MakeName(int index) { }

	// RVA: 0x31DF6C4 Offset: 0x31DB6C4 VA: 0x31DF6C4
	private void OnCollectionChanged(CollectionChangeEventArgs ccevent) { }

	// RVA: 0x31DE3D8 Offset: 0x31DA3D8 VA: 0x31DE3D8
	internal void RegisterName(string name) { }

	// RVA: 0x31E04D8 Offset: 0x31DC4D8 VA: 0x31E04D8
	public void Remove(Constraint constraint) { }

	// RVA: 0x31DE5C0 Offset: 0x31DA5C0 VA: 0x31DE5C0
	internal void UnregisterName(string name) { }
}
