// Assembly: System.Data.dll
// Namespace: System.Data
internal sealed class XmlTreeGen // TypeDefIndex: 14793
{
	// Fields
	private ArrayList _constraintNames; // 0x10
	private Hashtable _namespaces; // 0x18
	private Hashtable _autogenerated; // 0x20
	private Hashtable _prefixes; // 0x28
	private DataSet _ds; // 0x30
	private ArrayList _tables; // 0x38
	private ArrayList _relations; // 0x40
	private XmlDocument _dc; // 0x48
	private XmlElement _sRoot; // 0x50
	private int _prefixCount; // 0x58
	private SchemaFormat _schFormat; // 0x5C
	private string _filePath; // 0x60
	private string _fileName; // 0x68
	private string _fileExt; // 0x70
	private XmlElement _dsElement; // 0x78
	private XmlElement _constraintSeparator; // 0x80
	private Converter<Type, string> _targetConverter; // 0x88

	// Methods

	// RVA: 0x3233AEC Offset: 0x322FAEC VA: 0x3233AEC
	internal void .ctor(SchemaFormat format) { }

	// RVA: 0x3233B98 Offset: 0x322FB98 VA: 0x3233B98
	internal static void AddExtendedProperties(PropertyCollection props, XmlElement node) { }

	// RVA: 0x3233BA0 Offset: 0x322FBA0 VA: 0x3233BA0
	internal static void AddExtendedProperties(PropertyCollection props, XmlElement node, Type type) { }

	// RVA: 0x3234314 Offset: 0x3230314 VA: 0x3234314
	internal void AddXdoProperties(object instance, XmlElement root, XmlDocument xd) { }

	// RVA: 0x32344C4 Offset: 0x32304C4 VA: 0x32344C4
	internal void AddXdoProperty(PropertyDescriptor pd, object instance, XmlElement root, XmlDocument xd) { }

	// RVA: 0x3234DF0 Offset: 0x3230DF0 VA: 0x3234DF0
	internal static string XmlDataTypeName(Type type) { }

	// RVA: 0x3235CB8 Offset: 0x3231CB8 VA: 0x3235CB8
	private void GenerateConstraintNames(DataTable table, bool fromTable) { }

	// RVA: 0x32361D4 Offset: 0x32321D4 VA: 0x32361D4
	private void GenerateConstraintNames(ArrayList tables) { }

	// RVA: 0x32362CC Offset: 0x32322CC VA: 0x32362CC
	private void GenerateConstraintNames(DataSet ds) { }

	// RVA: 0x32365B0 Offset: 0x32325B0 VA: 0x32365B0
	private static bool _PropsNotEmpty(PropertyCollection props) { }

	// RVA: 0x32365D8 Offset: 0x32325D8 VA: 0x32365D8
	private bool HaveExtendedProperties(DataSet ds) { }

	// RVA: 0x323675C Offset: 0x323275C VA: 0x323675C
	internal void WriteSchemaRoot(XmlDocument xd, XmlElement rootSchema, string targetNamespace) { }

	// RVA: 0x32369C0 Offset: 0x32329C0 VA: 0x32369C0
	internal static void ValidateColumnMapping(Type columnType) { }

	// RVA: 0x3236A48 Offset: 0x3232A48 VA: 0x3236A48
	internal void SetupAutoGenerated(DataSet ds) { }

	// RVA: 0x3237760 Offset: 0x3233760 VA: 0x3237760
	internal void SetupAutoGenerated(ArrayList dt) { }

	// RVA: 0x3236D28 Offset: 0x3232D28 VA: 0x3236D28
	internal void SetupAutoGenerated(DataTable dt) { }

	// RVA: 0x3237EA8 Offset: 0x3233EA8 VA: 0x3237EA8
	private void CreateTablesHierarchy(DataTable dt) { }

	// RVA: 0x323822C Offset: 0x323422C VA: 0x323822C
	private void CreateRelations(DataTable dt) { }

	// RVA: 0x3238584 Offset: 0x3234584 VA: 0x3238584
	private DataTable[] CreateToplevelTables() { }

	// RVA: 0x3238870 Offset: 0x3234870 VA: 0x3238870
	internal void SchemaTree(XmlDocument xd, XmlWriter xmlWriter, DataSet ds, DataTable dt, bool writeHierarchy) { }

	// RVA: 0x323BCA4 Offset: 0x3237CA4 VA: 0x323BCA4
	internal XmlElement SchemaTree(XmlDocument xd, DataTable dt) { }

	// RVA: 0x323B000 Offset: 0x3237000 VA: 0x323B000
	internal XmlElement FillDataSetElement(XmlDocument xd, DataSet ds, DataTable dt) { }

	// RVA: 0x323EB54 Offset: 0x323AB54 VA: 0x323EB54
	internal void SetPath(XmlWriter xw) { }

	// RVA: 0x323ED8C Offset: 0x323AD8C VA: 0x323ED8C
	internal void Save(DataSet ds, XmlWriter xw) { }

	// RVA: 0x323EDAC Offset: 0x323ADAC VA: 0x323EDAC
	internal void Save(DataTable dt, XmlWriter xw) { }

	// RVA: 0x323EDA0 Offset: 0x323ADA0 VA: 0x323EDA0
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw) { }

	// RVA: 0x323EE6C Offset: 0x323AE6C VA: 0x323EE6C
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy) { }

	// RVA: 0x323EE78 Offset: 0x323AE78 VA: 0x323EE78
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy, Converter<Type, string> multipleTargetConverter) { }

	// RVA: 0x323B6E0 Offset: 0x32376E0 VA: 0x323B6E0
	internal XmlElement HandleRelation(DataRelation rel, XmlDocument dc) { }

	// RVA: 0x323EFD8 Offset: 0x323AFD8 VA: 0x323EFD8
	private static XmlElement FindSimpleType(XmlElement schema, string name) { }

	// RVA: 0x323F0CC Offset: 0x323B0CC VA: 0x323F0CC
	internal XmlElement GetSchema(string NamespaceURI) { }

	// RVA: 0x323F360 Offset: 0x323B360 VA: 0x323F360
	internal void HandleColumnType(DataColumn col, XmlDocument dc, XmlElement root, XmlElement schema) { }

	// RVA: 0x323F7DC Offset: 0x323B7DC VA: 0x323F7DC
	internal void AddColumnProperties(DataColumn col, XmlElement root) { }

	// RVA: 0x323FDE8 Offset: 0x323BDE8 VA: 0x323FDE8
	private string FindTargetNamespace(DataTable table) { }

	// RVA: 0x323FEF8 Offset: 0x323BEF8 VA: 0x323FEF8
	internal XmlElement HandleColumn(DataColumn col, XmlDocument dc, XmlElement schema, bool fWriteOrdinal) { }

	// RVA: 0x3240BD0 Offset: 0x323CBD0 VA: 0x3240BD0
	internal static string TranslateAcceptRejectRule(AcceptRejectRule rule) { }

	// RVA: 0x3240C40 Offset: 0x323CC40 VA: 0x3240C40
	internal static string TranslateRule(Rule rule) { }

	// RVA: 0x323B628 Offset: 0x3237628 VA: 0x323B628
	internal void AppendChildWithoutRef(XmlElement node, string Namespace, XmlElement el, string refString) { }

	// RVA: 0x3240A08 Offset: 0x323CA08 VA: 0x3240A08
	internal XmlElement FindTypeNode(XmlElement node, string strType) { }

	// RVA: 0x323B620 Offset: 0x3237620 VA: 0x323B620
	internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema) { }

	// RVA: 0x3240CF8 Offset: 0x323CCF8 VA: 0x3240CF8
	private bool HasMixedColumns(DataTable table) { }

	// RVA: 0x3237854 Offset: 0x3233854 VA: 0x3237854
	internal static bool AutoGenerated(DataColumn col) { }

	// RVA: 0x3241090 Offset: 0x323D090 VA: 0x3241090
	internal static bool AutoGenerated(DataRelation rel) { }

	// RVA: 0x3237DD4 Offset: 0x3233DD4 VA: 0x3237DD4
	internal static bool AutoGenerated(UniqueConstraint unique) { }

	// RVA: 0x3237DC8 Offset: 0x3233DC8 VA: 0x3237DC8
	private bool AutoGenerated(ForeignKeyConstraint fk) { }

	// RVA: 0x3241174 Offset: 0x323D174 VA: 0x3241174
	internal static bool AutoGenerated(ForeignKeyConstraint fk, bool checkRelation) { }

	// RVA: 0x32412B4 Offset: 0x323D2B4 VA: 0x32412B4
	private bool IsAutoGenerated(object o) { }

	// RVA: 0x323C170 Offset: 0x3238170 VA: 0x323C170
	internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema, bool genNested) { }

	// RVA: 0x3235AD4 Offset: 0x3231AD4 VA: 0x3235AD4
	private void SetMSDataAttribute(XmlElement root, Type type) { }
}
